name: Build iOS Only

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          # تغییر مهم: استفاده از نسخه 1.24 برای هماهنگی با کتابخانه موبایل
          go-version: '1.24'
          check-latest: true

      - name: Install Gomobile Tool
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init

      - name: Prepare Dependencies
        run: |
          # اضافه کردن صریح پکیج بایند
          go get golang.org/x/mobile/bind
          
          # تمیزکاری فایل وابستگی‌ها
          go mod tidy
          
          # تکنیک اصلی: کپی کردن وابستگی‌ها به داخل پوشه پروژه (Vendor)
          # این کار باعث می‌شود gomobile حتماً فایل‌ها را پیدا کند
          go mod vendor

      - name: Build XCFramework for iOS
        run: |
          # بیلد گرفتن با استفاده از فایل‌های لوکال (Vendor)
          gomobile bind -target=ios -ldflags="-s -w" -o LibXray.xcframework .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LibXray-iOS
          path: LibXray.xcframework
          compression-level: 9
