name: Build iOS Only

on:
  workflow_dispatch: # امکان اجرا دستی با دکمه
  push:
    branches: [ "main" ] # اجرا با هر کامیت (اختیاری)

jobs:
  build-ios:
    runs-on: macos-latest # برای بیلد iOS حتماً مک نیاز است

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23' # نسخه پایدار و جدید گو
          check-latest: true

      - name: Install Gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init

      - name: Download Dependencies
        run: |
          go mod download
          go mod tidy

      - name: Build XCFramework for iOS
        run: |
          # دستور اصلی بیلد فقط برای iOS
          # فلگ -s -w حجم فایل را کم می‌کند
          gomobile bind -target=ios -ldflags="-s -w" -o LibXray.xcframework .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LibXray-iOS
          path: LibXray.xcframework
          compression-level: 9
